package interfaces;

import java.util.List;
import javax.swing.JOptionPane;
import logica.Cliente;
import logica.GestorDatos;
import logica.Mascota;


public class CRUD_Mascotas extends javax.swing.JPanel {
    private GestorDatos gestordatos;
    private List<Cliente> listaClientes;
    private List<Mascota> listaMascotas;
    private int mascotaIndex;
    
    /**
     * Creates new form CRUD_Clientes
     */
    public CRUD_Mascotas(GestorDatos gestordatos) {
        initComponents();
        
        this.gestordatos = gestordatos;
        this.listaClientes = gestordatos.getListaClientes();
        this.listaMascotas = gestordatos.getListaMascotas();
        this.mascotaIndex = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDireccion = new javax.swing.JLabel();
        lbDatosCliente = new javax.swing.JLabel();
        lbNombreCliente = new javax.swing.JLabel();
        lbContacto = new javax.swing.JLabel();
        txtCondiciones = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtNombreMascota = new javax.swing.JTextField();
        lbNombreMascota = new javax.swing.JLabel();
        sPeso = new javax.swing.JSpinner();
        lbContacto1 = new javax.swing.JLabel();
        lbContacto2 = new javax.swing.JLabel();
        sEdad = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 569));
        setMinimumSize(new java.awt.Dimension(1280, 569));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 569));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDireccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lbDireccion.setText("Condiciones");
        add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        lbDatosCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDatosCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbDatosCliente.setText("Datos de la mascota");
        add(lbDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lbNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbNombreCliente.setText("Nombre del dueño");
        add(lbNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        lbContacto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbContacto.setForeground(new java.awt.Color(0, 0, 0));
        lbContacto.setText("Peso");
        add(lbContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        txtCondiciones.setBackground(new java.awt.Color(255, 255, 255));
        txtCondiciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCondiciones.setForeground(new java.awt.Color(0, 0, 0));
        add(txtCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 410, 30));

        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 260, 30));

        txtRaza.setBackground(new java.awt.Color(255, 255, 255));
        txtRaza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRaza.setForeground(new java.awt.Color(0, 0, 0));
        add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 130, 30));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        btnAnadir.setBackground(new java.awt.Color(0, 102, 102));
        btnAnadir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir.setText("AÑADIR");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        txtNombreMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreMascota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        add(txtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 270, 30));

        lbNombreMascota.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        lbNombreMascota.setText("Nombre de la mascota");
        add(lbNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        sPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sPeso.setModel(new javax.swing.SpinnerNumberModel());
        sPeso.setBorder(null);
        add(sPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        lbContacto1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbContacto1.setForeground(new java.awt.Color(0, 0, 0));
        lbContacto1.setText("Raza");
        add(lbContacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        lbContacto2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbContacto2.setForeground(new java.awt.Color(0, 0, 0));
        lbContacto2.setText("Edad");
        add(lbContacto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        sEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sEdad.setModel(new javax.swing.SpinnerNumberModel());
        sEdad.setBorder(null);
        add(sEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        boolean clienteExiste = false;
        String nombreCliente = txtNombreCliente.getText();
        
        for (Cliente cliente : listaClientes) {
            if (cliente.getNombre().equals(nombreCliente)) {
                clienteExiste = true;
                break;
            }
        }
        
        if (clienteExiste){
            String nombreMascota = txtNombreMascota.getText();
            String raza = txtRaza.getText();
            String condiciones = txtCondiciones.getText();
            int edad = (int) sEdad.getValue();
            int peso = (int) sPeso.getValue();

            if (nombreCliente == null || nombreCliente.isEmpty() || nombreMascota == null || nombreMascota.isEmpty() || raza == null || raza.isEmpty() || condiciones == null || condiciones.isEmpty() || edad == 0 || peso == 0) {
                JOptionPane.showMessageDialog(this, "No deben de haber espacios en blanco", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Mascota nuevaMascota = new Mascota(nombreCliente, nombreMascota, raza, edad, peso, condiciones);
                listaMascotas.add(nuevaMascota);
                gestordatos.escribirMascotas(listaMascotas);
                gestordatos.setListaMascotas(listaMascotas);
                JOptionPane.showMessageDialog(this, "Mascota añadida", "Success", JOptionPane.INFORMATION_MESSAGE);
            }            
        } else {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean mascotaExiste = false;
        String nombreMascota = txtNombreMascota.getText();
        int index = 0;

        for (Mascota mascota : listaMascotas) {
            if (mascota.getNombre().equals(nombreMascota)) {
                mascotaExiste = true;
                mascotaIndex = index;
                txtNombreCliente.setText(mascota.getDuenno());
                txtRaza.setText(mascota.getRaza());
                txtCondiciones.setText(mascota.getCondiciones());
                sEdad.setValue(mascota.getEdad());
                sPeso.setValue(mascota.getPeso());
                break;
            } else {
                index++;
            }
        }
        
        if (!mascotaExiste) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado la mascota", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (this.mascotaIndex == -1){
            JOptionPane.showMessageDialog(this, "Ninguna mascota seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean clienteExiste = false;
            String nombreCliente = txtNombreCliente.getText();

            for (Cliente cliente : listaClientes) {
                if (cliente.getNombre().equals(nombreCliente)) {
                    clienteExiste = true;
                    break;
                }
            }
            
            if (clienteExiste){
                String nombreMascota = txtNombreMascota.getText();
                String raza = txtRaza.getText();
                String condiciones = txtCondiciones.getText();
                int edad = (int) sEdad.getValue();
                int peso = (int) sPeso.getValue();

                if (nombreCliente == null || nombreCliente.isEmpty() || nombreMascota == null || nombreMascota.isEmpty() || raza == null || raza.isEmpty() || condiciones == null || condiciones.isEmpty() || edad == 0 || peso == 0) {
                    JOptionPane.showMessageDialog(this, "No deben de haber espacios en blanco", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    Mascota mascotaModificada = new Mascota(nombreCliente, nombreMascota, raza, edad, peso, condiciones);
                    listaMascotas.set(mascotaIndex, mascotaModificada);
                    gestordatos.escribirMascotas(listaMascotas);
                    gestordatos.setListaMascotas(listaMascotas);
                    JOptionPane.showMessageDialog(this, "Datos mascota modificados", "Success", JOptionPane.INFORMATION_MESSAGE);
                    mascotaIndex = -1;
                }            
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }  
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (this.mascotaIndex == -1){
            JOptionPane.showMessageDialog(this, "Ninguna mascota seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {            
            listaMascotas.remove(mascotaIndex);
            gestordatos.escribirMascotas(listaMascotas);
            gestordatos.setListaMascotas(listaMascotas);
            JOptionPane.showMessageDialog(this, "Mascota eliminada", "Success", JOptionPane.INFORMATION_MESSAGE);
            mascotaIndex = -1;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lbContacto;
    private javax.swing.JLabel lbContacto1;
    private javax.swing.JLabel lbContacto2;
    private javax.swing.JLabel lbDatosCliente;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombreMascota;
    private javax.swing.JSpinner sEdad;
    private javax.swing.JSpinner sPeso;
    private javax.swing.JTextField txtCondiciones;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
