package interfaces;

import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import logica.*;

public class CRUD_Clientes extends javax.swing.JPanel {
    private GestorDatos gestordatos;
    private List<Cliente> listaClientes;
    private int clienteIndex;
    /**
     * Creates new form CRUD_Clientes
     */
    public CRUD_Clientes(GestorDatos gestordatos) {
        initComponents();
        
        this.gestordatos = gestordatos;
        this.listaClientes = gestordatos.getListaClientes();
        this.clienteIndex = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDireccion = new javax.swing.JLabel();
        lbDatosCliente = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbContacto = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 569));
        setMinimumSize(new java.awt.Dimension(1280, 569));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDireccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lbDireccion.setText("Dirección");
        add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        lbDatosCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDatosCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbDatosCliente.setText("Datos del cliente");
        add(lbDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        lbNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("Nombre");
        add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        lbContacto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbContacto.setForeground(new java.awt.Color(0, 0, 0));
        lbContacto.setText("Contacto");
        add(lbContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 460, 30));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 260, 30));

        txtContacto.setBackground(new java.awt.Color(255, 255, 255));
        txtContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContacto.setForeground(new java.awt.Color(0, 0, 0));
        txtContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactoKeyTyped(evt);
            }
        });
        add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 130, 30));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        btnAnadir.setBackground(new java.awt.Color(0, 102, 102));
        btnAnadir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir.setText("AÑADIR");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        if (txtContacto.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContactoKeyTyped

      
    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        String nombre = txtNombre.getText();
        String contacto = txtContacto.getText();
        String direccion = txtDireccion.getText();
  
        if (nombre == null || nombre.isEmpty() || contacto == null || contacto.isEmpty() || direccion == null || direccion.isEmpty()) {
            // El nombre, contacto o dirección es nulo o está vacío
            JOptionPane.showMessageDialog(this, "No deben de haber espacios en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Cliente nuevoCliente = new Cliente(nombre, direccion, contacto);
            listaClientes.add(nuevoCliente);
            gestordatos.escribirClientes(listaClientes);
            gestordatos.setListaClientes(listaClientes);
            JOptionPane.showMessageDialog(this, "Cliente añadido", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (this.clienteIndex == -1){
            JOptionPane.showMessageDialog(this, "Ningún cliente seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String nombre = txtNombre.getText();
            String contacto = txtContacto.getText();
            String direccion = txtDireccion.getText();
            
            if (nombre == null || nombre.isEmpty() || contacto == null || contacto.isEmpty() || direccion == null || direccion.isEmpty()) {
                // El nombre, contacto o dirección es nulo o está vacío
                JOptionPane.showMessageDialog(this, "No deben de haber espacios en blanco", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Cliente clienteModificado = new Cliente(nombre, direccion, contacto);
                listaClientes.set(clienteIndex, clienteModificado);
                gestordatos.escribirClientes(listaClientes);
                gestordatos.setListaClientes(listaClientes);
                JOptionPane.showMessageDialog(this, "Datos cliente modificados", "Success", JOptionPane.INFORMATION_MESSAGE);
                clienteIndex = -1;
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean clienteExiste = false;
        String nombre = txtNombre.getText();
        
        int index = 0;
        for (Cliente cliente : listaClientes) {
            if (cliente.getNombre().equals(nombre)) {
                txtContacto.setText(cliente.getContacto());
                txtDireccion.setText(cliente.getDireccion());
                this.clienteIndex = index;
                break;
            } else {
                index++;
            }
        }
        
        if (!clienteExiste) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (this.clienteIndex == -1){
            JOptionPane.showMessageDialog(this, "Ningún cliente seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {        
            listaClientes.remove(clienteIndex);
            gestordatos.escribirClientes(listaClientes);
            gestordatos.setListaClientes(listaClientes);
            JOptionPane.showMessageDialog(this, "Cliente eliminado", "Success", JOptionPane.INFORMATION_MESSAGE);
            clienteIndex = -1;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lbContacto;
    private javax.swing.JLabel lbDatosCliente;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
