package interfaces;

import logica.GestorDatos;

public class PantallaPrincipal extends javax.swing.JFrame {
    private GestorDatos gestordatos;
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        gestordatos = new GestorDatos();
        
        gestordatos.setListaCitas(gestordatos.leerCitas());
        gestordatos.setListaMascotas(gestordatos.leerMascotas());
        gestordatos.setListaClientes(gestordatos.leerClientes());
        gestordatos.setListaHistorialesClinicos(gestordatos.leerHistorialesMedicos());
        
        System.out.println(gestordatos.getListaCitas() + "\n" + gestordatos.getListaClientes() + "\n" + gestordatos.getListaMascotas() + "\n" + gestordatos.getListaHistorialesClinicos());
        
        CRUD_Clientes crudClientes = new CRUD_Clientes(gestordatos);
        crudClientes.setSize(1280,569);
        crudClientes.setLocation(0,0);
        
        pCRUDClientes.removeAll();
        pCRUDClientes.add(crudClientes);
        pCRUDClientes.revalidate();
        pCRUDClientes.repaint();
        
        CRUD_Mascotas crudMascotas = new CRUD_Mascotas(gestordatos);
        crudMascotas.setSize(1280,569);
        crudMascotas.setLocation(0,0);
        
        pCRUDMascotas.removeAll();
        pCRUDMascotas.add(crudMascotas);
        pCRUDMascotas.revalidate();
        pCRUDMascotas.repaint();
        
        CRUD_Citas crudCitas = new CRUD_Citas(gestordatos);
        crudCitas.setSize(1280,569);
        crudCitas.setLocation(0,0);
        
        pCRUDCitas.removeAll();
        pCRUDCitas.add(crudCitas);
        pCRUDCitas.revalidate();
        pCRUDCitas.repaint();
        
        PaginaHistorial historial = new PaginaHistorial(gestordatos);
        historial.setSize(1280,569);
        historial.setLocation(0,0);
        
        pPaginaHistorial.removeAll();
        pPaginaHistorial.add(historial);
        pPaginaHistorial.revalidate();
        pPaginaHistorial.repaint();
        
        PaginaReportes reportes = new PaginaReportes(gestordatos);
        reportes.setSize(1280,569);
        reportes.setLocation(0,0);
        
        pReportes.removeAll();
        pReportes.add(reportes);
        pReportes.revalidate();
        pReportes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTopPanel = new javax.swing.JPanel();
        lbSubtitle = new javax.swing.JLabel();
        lbMainTitle = new javax.swing.JLabel();
        tpPanelPrincipal = new javax.swing.JTabbedPane();
        pPaginaPrincipal = new javax.swing.JPanel();
        lbWelcome = new javax.swing.JLabel();
        lbWelcome1 = new javax.swing.JLabel();
        pCRUDClientes = new javax.swing.JPanel();
        pCRUDMascotas = new javax.swing.JPanel();
        pCRUDCitas = new javax.swing.JPanel();
        pPaginaHistorial = new javax.swing.JPanel();
        pReportes = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pTopPanel.setBackground(new java.awt.Color(0, 102, 102));
        pTopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSubtitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lbSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubtitle.setText("Página principal");
        pTopPanel.add(lbSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 560, 30));

        lbMainTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbMainTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbMainTitle.setText("Veterinaria Mascotitas");
        pTopPanel.add(lbMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 550, 80));

        getContentPane().add(pTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 120));

        tpPanelPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        tpPanelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        tpPanelPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        pPaginaPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        pPaginaPrincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pPaginaPrincipalComponentShown(evt);
            }
        });

        lbWelcome.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(0, 0, 0));
        lbWelcome.setText("DE NUETRA VETERINARIA");

        lbWelcome1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbWelcome1.setForeground(new java.awt.Color(0, 0, 0));
        lbWelcome1.setText("BIENVENIDO A LA APLICACIÓN");

        javax.swing.GroupLayout pPaginaPrincipalLayout = new javax.swing.GroupLayout(pPaginaPrincipal);
        pPaginaPrincipal.setLayout(pPaginaPrincipalLayout);
        pPaginaPrincipalLayout.setHorizontalGroup(
            pPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPaginaPrincipalLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(pPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230))
        );
        pPaginaPrincipalLayout.setVerticalGroup(
            pPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPaginaPrincipalLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(lbWelcome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWelcome)
                .addGap(281, 281, 281))
        );

        tpPanelPrincipal.addTab("Bienvenida", pPaginaPrincipal);

        pCRUDClientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pCRUDClientesComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pCRUDClientesLayout = new javax.swing.GroupLayout(pCRUDClientes);
        pCRUDClientes.setLayout(pCRUDClientesLayout);
        pCRUDClientesLayout.setHorizontalGroup(
            pCRUDClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pCRUDClientesLayout.setVerticalGroup(
            pCRUDClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tpPanelPrincipal.addTab("Clientes", pCRUDClientes);

        pCRUDMascotas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pCRUDMascotasComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pCRUDMascotasLayout = new javax.swing.GroupLayout(pCRUDMascotas);
        pCRUDMascotas.setLayout(pCRUDMascotasLayout);
        pCRUDMascotasLayout.setHorizontalGroup(
            pCRUDMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pCRUDMascotasLayout.setVerticalGroup(
            pCRUDMascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tpPanelPrincipal.addTab("Mascotas", pCRUDMascotas);

        pCRUDCitas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pCRUDCitasComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pCRUDCitasLayout = new javax.swing.GroupLayout(pCRUDCitas);
        pCRUDCitas.setLayout(pCRUDCitasLayout);
        pCRUDCitasLayout.setHorizontalGroup(
            pCRUDCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pCRUDCitasLayout.setVerticalGroup(
            pCRUDCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tpPanelPrincipal.addTab("Citas", pCRUDCitas);

        pPaginaHistorial.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pPaginaHistorialComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pPaginaHistorialLayout = new javax.swing.GroupLayout(pPaginaHistorial);
        pPaginaHistorial.setLayout(pPaginaHistorialLayout);
        pPaginaHistorialLayout.setHorizontalGroup(
            pPaginaHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pPaginaHistorialLayout.setVerticalGroup(
            pPaginaHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tpPanelPrincipal.addTab("Historial Clinico", pPaginaHistorial);

        pReportes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pReportesComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pReportesLayout = new javax.swing.GroupLayout(pReportes);
        pReportes.setLayout(pReportesLayout);
        pReportesLayout.setHorizontalGroup(
            pReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pReportesLayout.setVerticalGroup(
            pReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tpPanelPrincipal.addTab("Reportes", pReportes);
        tpPanelPrincipal.addTab("tab7", jTabbedPane1);

        getContentPane().add(tpPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1280, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pCRUDClientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pCRUDClientesComponentShown
        lbSubtitle.setText("Gestión de clientes");
    }//GEN-LAST:event_pCRUDClientesComponentShown

    private void pCRUDMascotasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pCRUDMascotasComponentShown
        lbSubtitle.setText("Gestión de mascotas");
    }//GEN-LAST:event_pCRUDMascotasComponentShown

    private void pPaginaPrincipalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pPaginaPrincipalComponentShown
        lbSubtitle.setText("Página Principal");
    }//GEN-LAST:event_pPaginaPrincipalComponentShown

    private void pCRUDCitasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pCRUDCitasComponentShown
        lbSubtitle.setText("Gestión de citas");
    }//GEN-LAST:event_pCRUDCitasComponentShown

    private void pReportesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pReportesComponentShown
        lbSubtitle.setText("Reportes");
    }//GEN-LAST:event_pReportesComponentShown

    private void pPaginaHistorialComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pPaginaHistorialComponentShown
        lbSubtitle.setText("Historial clínico");
    }//GEN-LAST:event_pPaginaHistorialComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbMainTitle;
    private javax.swing.JLabel lbSubtitle;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel lbWelcome1;
    private javax.swing.JPanel pCRUDCitas;
    private javax.swing.JPanel pCRUDClientes;
    private javax.swing.JPanel pCRUDMascotas;
    private javax.swing.JPanel pPaginaHistorial;
    private javax.swing.JPanel pPaginaPrincipal;
    private javax.swing.JPanel pReportes;
    private javax.swing.JPanel pTopPanel;
    private javax.swing.JTabbedPane tpPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
